In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


Importing the Data Set

In [2]:
df = pd.read_csv(r"D:\Vishu\My\Innomatics\New\housing_price_dataset.csv")

In [3]:
df

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [4]:
df.head()

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [5]:
df.dtypes

SquareFeet        int64
Bedrooms          int64
Bathrooms         int64
Neighborhood     object
YearBuilt         int64
Price           float64
dtype: object

In [6]:
df.info

<bound method DataFrame.info of        SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]>

In [7]:
df.isna().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df["Neighborhood"] = df["Neighborhood"].map({'Rural':1, 'Suburb':2,'Urban':3})

In [10]:
df.head()

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0        2126         4          1             1       1969  215355.283618
1        2459         3          2             1       1980  195014.221626
2        1860         2          1             2       1970  306891.012076
3        2294         2          1             3       1996  206786.787153
4        2130         5          2             2       2001  272436.239065

### Model Building

Spliting into output and output

In [11]:
X = df.drop('Price',axis=1)
y = df['Price']

Spliting into train and Test

In [12]:
!pip install scikit-learn

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
train_test_split(X,y,train_size=0.8)

[       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 27345        2839         4          2             3       1970
 44839        1793         4          2             1       1990
 20292        2180         3          2             1       2015
 15963        1862         5          3             2       1974
 35447        2316         2          2             3       1970
 ...           ...       ...        ...           ...        ...
 24071        1105         3          3             3       1969
 38953        1517         4          3             1       1983
 17144        2236         4          3             1       1971
 43631        2939         5          2             1       1951
 3476         1231         5          2             3       1986
 
 [40000 rows x 5 columns],
        SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 31172        2300         2          1             2       1995
 48280        1101         5          2             2       1

In [15]:
train_test_split(X,y,test_size=0.2, random_state=23)

[       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 20198        2169         2          3             1       1988
 34103        2568         3          2             2       1977
 40179        1339         3          3             1       1958
 34586        2716         2          1             1       1978
 30725        2307         3          1             1       1974
 ...           ...       ...        ...           ...        ...
 9704         2788         4          3             2       1986
 11190        2557         5          1             2       2004
 26569        2344         3          2             1       1961
 9256         1105         5          2             2       2008
 41555        2248         2          3             3       2020
 
 [40000 rows x 5 columns],
        SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 49466        1055         3          2             1       1969
 11621        1754         4          3             1       1

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=23)

In [17]:
X_train.shape

(40000, 5)

In [18]:
X_test.shape

(10000, 5)

In [19]:
y_train.shape

(40000,)

In [20]:
y_test.shape

(10000,)

### KNN, Linear Regression, SVM, DT

KNN

In [21]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error,r2_score

In [22]:
knn = KNeighborsRegressor()
knn.fit(X_train,y_train)

KNeighborsRegressor()

In [23]:
knn = KNeighborsRegressor()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

54247.93901533543


Evaluating

In [24]:
from sklearn.metrics import mean_squared_error,r2_score

In [25]:
mean_squared_error(y_test,y_pred)

2942838887.4115524

In [26]:
np.sqrt(mean_squared_error(y_test,y_pred))

54247.93901533543

Liner Regression

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

49403.976927995944


In [29]:
from sklearn.svm import SVR

In [30]:
''' sv = SVR()
sv.fit(X_train,y_train)
y_pred = sv.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))'''

' sv = SVR()\nsv.fit(X_train,y_train)\ny_pred = sv.predict(X_test)\nprint(np.sqrt(mean_squared_error(y_test,y_pred)))'

Decision Tree

In [31]:
from sklearn.tree import DecisionTreeRegressor

In [32]:
dt = DecisionTreeRegressor()
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

72533.94079803275


In [33]:
lr.predict([[2650,3,2,4,1950]])

C:\Users\gorla\anaconda3\desktop\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([288048.77360633])

In [34]:
lr.predict([[2650,3,2,2,1950]])[0]

C:\Users\gorla\anaconda3\desktop\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


286544.24985249375

In [35]:
lr.coef_

array([  99.31308607, 5168.85659283, 2625.12603247,  752.26187692,
        -13.64933459])

In [36]:
lr.intercept_

27719.428600464948

In [37]:
sqft = 2650
bed = 3
bath = 2
nb = 2
year = 1950

price = 99.31308607 * sqft +  5168.85659283 *bed + 2625.12603247*bath +752.26187692* nb -13.64933459 * year + 27719.4286004623
print(price)

286544.24983273225


## Pickling

In [38]:
import pickle

In [39]:
pickle.dump(lr,open("lr.pkl","wb"))  # writing as a binary format

In [40]:
model = pickle.load(open("lr.pkl","rb"))

In [41]:
model.predict([[2126,4,1,1,1969]])

C:\Users\gorla\anaconda3\desktop\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([236036.32407558])